insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Konon', 3, 'Bardzo dobre, smaczne.', 2, 'dieta');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Major', 4, 'Pszne', 5, 'przepis');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Meksikano', 2, 'Bardzo dobre, pozdrawiam, wiecie o kogo chodzi', 8, 'dieta');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Nero', 1, 'How how', 1, 'przepis');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Ewa Boza', 1, 'Dobre', 4, 'dieta');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Pan Tomasz', 1, 'Zaiste pyszne jest to', 5, 'przepis');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Rafonix', 5, 'Kupiłem flache, pojechalem do starego, pol litra krupnika wzialem', 3, 'dieta');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Daniel Magical', 4, 'Dobre, dobre', 7, 'przepis');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Pani Gosia', 5, 'Gud gud', 4, 'dieta');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Jaca', 3, 'Spoko, ale moglo byc lepsze', 1, 'przepis');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Pezet', 3, 'Srednio', 4, 'dieta');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Baobab', 2, 'Niedobre', 5, 'przepis');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Jachimek', 2, 'Slabe', 6, 'dieta');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Bebzon BMW', 3, 'Obrzydliwe, ale tanie', 9, 'przepis');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Sonia', 1, 'Nie polecam', 3, 'dieta');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Texas', 1, 'Straszne', 23, 'przepis');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Rafatus', 5, 'Polecam', 24, 'dieta');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Marlenka', 4, 'Polecam, dobre', 26, 'przepis');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Agnieszka', 2, 'Zle', 21, 'dieta');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'WuWunio', 3, 'Kocur', 24, 'przepis');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Sowa', 3, 'Sredniawka', 27, 'dieta');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Bonus BGC', 4, 'Git', 23, 'przepis');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Antos', 1, 'Wywalcie to', 26, 'dieta');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Body Christ', 2, 'Slabiutko', 21, 'przepis');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Gracjan Roztocki', 2, 'Ble', 12, 'dieta');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Tiger Bonzo', 4, 'Lobabeb', 22, 'przepis');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Kobra', 3, 'Ta dieta jest jak z zyciem na kociom lape', 23, 'dieta');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Lord Kruszwil', 2, 'Tanie i obrzydliwe', 42, 'przepis');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Kamerzysta', 1, 'Gdzie z tym badziewiem', 52, 'dieta');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Szofer', 2, 'Nie podoba mi sie', 62, 'przepis');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Sebastian Szwed', 3, 'Siwuple siwuple', 27, 'dieta');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Esmeralda Godlewska', 2, 'Nie mam nic do powiedzenia', 28, 'przepis');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Malgorzata Godlewska', 2, 'Slabiutko', 29, 'dieta');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Marta Linkiewicz', 5, 'Czarno na bialym, zajebiste', 12, 'przepis');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'DEYNN', 1, 'Ta dieta to chlam', 22, 'dieta');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Majewski', 1, 'Bilans sie nie zgadza', 32, 'przepis');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Janczar', 3, 'Takie se', 42, 'dieta');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Luiza', 3, 'Sredniawka', 52, 'przepis');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Fazi', 2, 'Ocena nieprzypadkowa', 62, 'dieta');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Pakol', 4, 'Kot', 72, 'przepis');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Oskar Pam Pam', 5, 'Pam pam', 82, 'dieta');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Bystrzak', 2, 'Niedobre', 92, 'przepis');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Siwy', 3, 'Takie sobie', 233, 'dieta');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Tajfun', 3, 'Ok', 221, 'przepis');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Esta', 4, 'Nawet nawet he', 212, 'dieta');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Rusek', 2, 'Obrzydliwe', 245, 'przepis');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Kaczor', 3, 'fadsfasd', 265, 'dieta');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Arsen', 2, 'Gdzie z tym do ludzi', 287, 'przepis');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Gural', 3, 'Smakuje', 299, 'dieta');
insert into Oceny(Data, Nick, Ocena, Tekst, resourceId, resourceName) values(SYSDATETIME(), 'Adrian Polak', 1, 'Daniel rzadzi', 24, 'przepis');

