// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Westeros.Ranking.Data.Repositories;

namespace Westeros.Ranking.Data.Migrations
{
    [DbContext(typeof(StarkDbContext))]
    [Migration("20181123221428_CreateDB")]
    partial class CreateDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Westeros.Ranking.Data.Model.Dieta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DietaId");

                    b.Property<int>("IloscOdwiedzin");

                    b.HasKey("Id");

                    b.ToTable("DietyOdwiedziny");
                });

            modelBuilder.Entity("Westeros.Ranking.Data.Model.Komentarz", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Data");

                    b.Property<string>("Nick");

                    b.Property<string>("Tekst");

                    b.HasKey("id");

                    b.ToTable("Komentarz");
                });

            modelBuilder.Entity("Westeros.Ranking.Data.Model.Przepis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("IloscOdwiedzin");

                    b.Property<int>("PrzepisId");

                    b.HasKey("Id");

                    b.ToTable("PrzepisyOdwiedziny");
                });
#pragma warning restore 612, 618
        }
    }
}
