// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Westeros.Ranking.Data.Repositories;

namespace Westeros.Ranking.Data.Migrations
{
    [DbContext(typeof(StarkDbContext))]
    [Migration("20190110185820_StarkDataBase")]
    partial class StarkDataBase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Westeros.Ranking.Data.Model.Dieta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DietaId");

                    b.Property<int>("IloscOdwiedzin");

                    b.HasKey("Id");

                    b.ToTable("DietyOdwiedziny");
                });

            modelBuilder.Entity("Westeros.Ranking.Data.Model.Oceny", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Data");

                    b.Property<string>("Nick")
                        .IsRequired();

                    b.Property<int>("Ocena");

                    b.Property<string>("Tekst")
                        .IsRequired();

                    b.Property<int>("resourceId");

                    b.Property<string>("resourceName");

                    b.HasKey("id");

                    b.ToTable("Oceny");
                });

            modelBuilder.Entity("Westeros.Ranking.Data.Model.Przepis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("IloscOdwiedzin");

                    b.Property<int>("PrzepisId");

                    b.HasKey("Id");

                    b.ToTable("PrzepisyOdwiedziny");
                });
#pragma warning restore 612, 618
        }
    }
}
