SET IDENTITY_INSERT [dbo].[MailServerDb] OFF
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)

INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'asdada', N'asd', NULL, N'2019-01-13 13:22:45', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)

INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'asdada', N'asd', NULL, N'2019-01-13 13:22:45', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)

INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'asdada', N'asd', NULL, N'2019-01-13 13:22:45', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)

INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'asdada', N'asd', NULL, N'2019-01-13 13:22:45', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)

INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'asdada', N'asd', NULL, N'2019-01-13 13:22:45', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)

INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'asdada', N'asd', NULL, N'2019-01-13 13:22:45', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)

INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'asdada', N'asd', NULL, N'2019-01-13 13:22:45', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)

INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'asdada', N'asd', NULL, N'2019-01-13 13:22:45', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)

INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'asdada', N'asd', NULL, N'2019-01-13 13:22:45', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)

INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'asdada', N'asd', NULL, N'2019-01-13 13:22:45', 0)

INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'Demo1', N'asdadsa', NULL, N'2019-01-12 19:05:28', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES (N'asdaas', N'asdada', N'asdas', NULL, N'2019-01-12 19:11:03', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'januszek', NULL, N'2019-01-13 13:08:26', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'demolinka', N'januszek1', NULL, N'2019-01-13 13:10:59', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'Demo1', N'demolinka', N'asd', N'benc', N'2019-01-13 13:22:36', 0)
INSERT INTO [dbo].[MailServerDb] ( [To], [From], [Content], [Topic], [Date], [IsNew]) VALUES ( N'kastus', N'asdada', N'asd', NULL, N'2019-01-13 13:22:45', 0)
SET IDENTITY_INSERT [dbo].[MailServerDb] OFF
